# Generated by Django 2.2.3 on 2019-07-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='created_by',
            new_name='owner',
        ),
    ]
