# Generated by Django 2.2.3 on 2019-07-31 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lots', '0003_auto_20190730_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='owner',
        ),
        migrations.AddField(
            model_name='lot',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
